core/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from .views import LandingPageView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("", include("library.urls")),
    path("", LandingPageView.as_view(), name="landing-page"),
]

library/urls.py
from django.urls import path
from .views import BookListView, BookDetailView

urlpatterns = [
    path('books/', BookListView.as_view(), name="books"),
    path("books/<int:id>/", BookDetailView.as_view(), name="detail"),
]

users/urls.py
from django.urls import path
from .views import UserLoginView, UserRegisterView, HomePageView, UserListView, UserDetailView, UserSettingsView, ProfileView

app_name = "users"
urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("register/", UserRegisterView.as_view(), name="register"),
    path("home/", HomePageView.as_view(), name="home"),
    path("users/", UserListView.as_view(), name="users"),
    path("users/<int:id>/", UserDetailView.as_view(), name="users-detail"),
    path("settings/<int:id>/", UserSettingsView.as_view(), name="settings"),
    path("profile/", ProfileView.as_view(), name="profile")
]

library/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=50, null=True)
    description = models.TextField()
    price = models.FloatField(default=1)
    count = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(100)], default=1)


class Customers(models.Model):
    ROLE = (
        ("student", "S"),
        ("teacher", "T"))
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    role = models.CharField(max_length=20, choices=ROLE, default="S")



class BookRecord(models.Model):
    customer = models.ForeignKey(Customers, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    returned_date = models.DateField(null=True, blank=True)
    create_date = models.DateTimeField(auto_created=True)

users/models.py
from django.db import models

users/forms.py
from django import forms
from django.contrib.auth.models import User

# Base Form
"""class UserRegisterForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.EmailField()
    username = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50)

    def save(self):
        first_name = self.cleaned_data["first_name"]
        last_name = self.cleaned_data["last_name"]
        email = self.cleaned_data["email"]
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]
        user = User.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            username=username
        )
        user.set_password(password)
        user.save()"""


class UserRegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password")

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data["password"])
        user.save()
        return user


class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=56)
    password = forms.CharField(max_length=50)

    def clean(self):
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]

core/views.py
from django.shortcuts import render
from django.views import View

class LandingPageView(View):
    def get(self, request):
        return render(request, "landing.html")

library/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from .models import Book

class BookListView(View):
    def get(self, request):
        search = request.GET.get("search")
        if not search:
            books = Book.objects.all()
            context = {
                "books": books
            }
            return render(request, "library/books.html", context)
        else:
            book = Book.objects.filter(title__icontains=search)
            if not book:
                return HttpResponse("<h3>Not Fount</h3>")
            else:
                context = {
                    "books": book,
                    "search": search
                }
                return render(request, "library/books.html", context)







class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        return render(request, "library/books_detail.html", context={"book": book})

users/views.py
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from .forms import UserRegisterForm, UserLoginForm

class HomePageView(View):
    def get(self, request):
        return render(request, "users/home.html")

class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm()
        context = {
            "form": form
        }
        return render(request, "users/login.html", context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect("users:home")
        else:
            context = {
                "form": login_form
            }
            return render(request, "users/login.html", context)


class UserRegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        context = {
            "form": form
        }
        return render(request, "users/register.html", context)

    def post(self, request):
        create_form = UserRegisterForm(data=request.POST)
        if create_form.is_valid():
            create_form.save()
            return redirect("users:login")
        else:
            print("Error")
            context = {
                "form": create_form
            }
            return render(request, "users/register.html", context)


class UserListView(View):
    def get(self, request):
        search = request.GET.get("search")
        if not search:
            users = User.objects.all()
            return render(request, "users/users.html", context={"users": users})
        else:
            user = User.objects.filter(first_name__icontains=search) | User.objects.filter(last_name__icontains=search)
            if not user:
                return HttpResponse("<h1>Not Fount</h1>")
            else:
                context = {
                    "users": user,
                    "search": search
                }
                return render(request, "users/users.html", context)


    def post(self):
        pass


class UserDetailView(View):
    def get(self, request, id):
        user = User.objects.get(id=id)
        return render(request, "users/user_detail.html", context={"user": user})

class UserSettingsView(View):
    def get(self, request, id):
        user = User.objects.get(id=id)
        return render(request, "users/settings.html", context={"user": user})

    def post(self, request, id):
        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        password = request.POST["password"]

        user = User.objects.get(id=id)
        user.first_name = first_name
        user.last_name = last_name
        user.set_password(password)
        user.save()
        return HttpResponse("<h1>Successfull</h1>")

class ProfileView(View):
    def get(self, request):
        return render(request, "users/profile.html", {"user": request.user})

templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Landing</title>
</head>
<body>
    <h1>Landing Page</h1>
    <p>
        <a href="{% url 'users:login' %}">Login</a> | <a href="{% url 'users:register' %}">Register</a>
    </p>
</body>
</html>

templates/library/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book</title>
</head>
<body>
    <h1>Books:</h1>
    <form action="">
        <input type="search" name="search" value="{{ search }}" placeholder="Search Book">
        <button type="submit">Search</button>

    </form>  <br>
    {% for book in books %}
        <li><a href="{% url 'detail' book.id %}">{{ book.title }}</a></li>
    {% endfor %}
    </ul>
</body>
</html>

templates/library/books_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>Title: {{ book.title }}</h2>
    <h3>Description:</h3>
    <p>
        {{ book.description }}
    </p>
    <h3>Price: {{ book.price }}</h3>

</body>
</html>

templates/not_fount.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Not Fount</h1>
</body>
</html>

templates/users/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Home Page</h1>
    <a href="{% url 'books' %}">Books</a> | <a href="{% url 'users:users' %}">Users</a>
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Login Page</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Log In</button>
    </form>
</body>
</html>

templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Profile Page</h1>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
  <h1>Register Page</h1>
  <form method="POST" action="">

      {% csrf_token %}
      {{ form.as_p }}

      <button type="submit">Submit</button>
  </form>
</body>
</html>

templates/users/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Settings</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <label for="first_name">First Name: </label>
        <input id="first_name" value="{{ user.first_name }}" name="first_name" type="text" placeholder="First Name"> <br> <br>

        <label for="last_name">Last Name: </label>
        <input id="last_name" type="text"  value="{{ user.last_name }}" name="last_name" placeholder="Last Name"> <br> <br>

        <label for="password">Password: </label>
        <input id="password" type="text" value="{{user.password}}" name="password" placeholder="Password"> <br> <br>

        <button type="submit">Change</button>
    </form>
</body>
</html>

templates/users/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>
        <h2>ID: {{user.id}}</h2>
        <h2>First Name: {{user.first_name}}</h2>
        <h2>LAst Name: {{user.last_name}}</h2>
        <h2>Username: {{user.username}}</h2>
        <h2>Password: ****</h2>
    </p>
    <a href="{% url 'users:settings' user.id %}">
        <button type="">Settings</button>
    </a>
</body>
</html>

templates/users/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>users:</h1>

    <form action="">
        <input type="search" name="search" value="{{ search }}" placeholder="Search User">
        <button type="submit">Search</button>
    </form>

    <ul>
        {% for user in users %}
            <li>
                <a href="{% url 'users:users-detail' user.id %}">{{user.username}} {{ user.first_name}} {{ user.last_name}}</a>
            </li>
        {% endfor %}
    </ul>

</body>
</html>